In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Libraries loaded! ✅")

Libraries loaded! ✅

In [2]:
df = pd.read_csv('/Users/abhinavjha/NeuralRetail/data/raw/online_retail.csv')
print(f"Shape: {df.shape} ✅")
df.head()

Shape: (541909, 8) ✅

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
print(df.columns.tolist())

['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

In [5]:
df = df.dropna(subset=['CustomerID'])
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]
df = df[df['Quantity'] > 0]
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
print(f"Clean data shape: {df.shape} ✅")
df.to_csv('/Users/abhinavjha/NeuralRetail/data/processed/clean_data.csv', index=False)
print("Clean data saved! ✅")
df.head()

Clean data shape: (397924, 9) ✅
Clean data saved! ✅

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [6]:
print("=== Sales Analysis ===")
print(f"Total Revenue: £{df['TotalPrice'].sum():,.2f}")
print(f"Total Orders: {df['InvoiceNo'].nunique():,}")
print(f"Total Customers: {df['CustomerID'].nunique():,}")
print(f"Total Products: {df['StockCode'].nunique():,}")
print(f"Countries: {df['Country'].nunique()}")

=== Sales Analysis ===
Total Revenue: £8,911,407.90
Total Orders: 18,536
Total Customers: 4,339
Total Products: 3,665
Countries: 37